/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Signos vitales medidos al ingreso.
 * @export
 * @interface CreateTriageEvaluationRequestVitalSigns
 */
export interface CreateTriageEvaluationRequestVitalSigns {
    /**
     * Frecuencia cardíaca (lpm).
     */
    heartRate?: number;
    /**
     * Presión arterial sistólica (mmHg).
     */
    bloodPressureSystolic?: number;
    /**
     * Presión arterial diastólica (mmHg).
     */
    bloodPressureDiastolic?: number;
    /**
     * Temperatura corporal en grados Celsius.
     */
    temperatureCelsius?: number;
    /**
     * Saturación de oxígeno (%).
     */
    oxygenSaturationPercentage?: number;
}

/**
 * Check if a given object implements the CreateTriageEvaluationRequestVitalSigns interface.
 */
export function instanceOfCreateTriageEvaluationRequestVitalSigns(value: object): value is CreateTriageEvaluationRequestVitalSigns {
    return true;
}

export function CreateTriageEvaluationRequestVitalSignsFromJSON(json: any): CreateTriageEvaluationRequestVitalSigns {
    return CreateTriageEvaluationRequestVitalSignsFromJSONTyped(json, false);
}

export function CreateTriageEvaluationRequestVitalSignsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTriageEvaluationRequestVitalSigns {
    if (json == null) {
        return json;
    }
    return {
        
        'heartRate': json['heartRate'] == null ? undefined : json['heartRate'],
        'bloodPressureSystolic': json['bloodPressureSystolic'] == null ? undefined : json['bloodPressureSystolic'],
        'bloodPressureDiastolic': json['bloodPressureDiastolic'] == null ? undefined : json['bloodPressureDiastolic'],
        'temperatureCelsius': json['temperatureCelsius'] == null ? undefined : json['temperatureCelsius'],
        'oxygenSaturationPercentage': json['oxygenSaturationPercentage'] == null ? undefined : json['oxygenSaturationPercentage'],
    };
}

export function CreateTriageEvaluationRequestVitalSignsToJSON(json: any): CreateTriageEvaluationRequestVitalSigns {
    return CreateTriageEvaluationRequestVitalSignsToJSONTyped(json, false);
}

export function CreateTriageEvaluationRequestVitalSignsToJSONTyped(value?: CreateTriageEvaluationRequestVitalSigns | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'heartRate': value['heartRate'],
        'bloodPressureSystolic': value['bloodPressureSystolic'],
        'bloodPressureDiastolic': value['bloodPressureDiastolic'],
        'temperatureCelsius': value['temperatureCelsius'],
        'oxygenSaturationPercentage': value['oxygenSaturationPercentage'],
    };
}

