/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateTriageEvaluationRequestVitalSigns } from './CreateTriageEvaluationRequestVitalSigns';
import {
    CreateTriageEvaluationRequestVitalSignsFromJSON,
    CreateTriageEvaluationRequestVitalSignsFromJSONTyped,
    CreateTriageEvaluationRequestVitalSignsToJSON,
    CreateTriageEvaluationRequestVitalSignsToJSONTyped,
} from './CreateTriageEvaluationRequestVitalSigns';

/**
 * 
 * @export
 * @interface CreateTriageEvaluationRequest
 */
export interface CreateTriageEvaluationRequest {
    /**
     * 
     */
    patientId: string;
    /**
     * Lista de síntomas reportados por el paciente o el personal de triage.
     */
    symptoms?: Array<string>;
    /**
     * 
     */
    vitalSigns: CreateTriageEvaluationRequestVitalSigns;
}

/**
 * Check if a given object implements the CreateTriageEvaluationRequest interface.
 */
export function instanceOfCreateTriageEvaluationRequest(value: object): value is CreateTriageEvaluationRequest {
    if (!('patientId' in value) || value['patientId'] === undefined) return false;
    if (!('vitalSigns' in value) || value['vitalSigns'] === undefined) return false;
    return true;
}

export function CreateTriageEvaluationRequestFromJSON(json: any): CreateTriageEvaluationRequest {
    return CreateTriageEvaluationRequestFromJSONTyped(json, false);
}

export function CreateTriageEvaluationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTriageEvaluationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'patientId': json['patientId'],
        'symptoms': json['symptoms'] == null ? undefined : json['symptoms'],
        'vitalSigns': CreateTriageEvaluationRequestVitalSignsFromJSON(json['vitalSigns']),
    };
}

export function CreateTriageEvaluationRequestToJSON(json: any): CreateTriageEvaluationRequest {
    return CreateTriageEvaluationRequestToJSONTyped(json, false);
}

export function CreateTriageEvaluationRequestToJSONTyped(value?: CreateTriageEvaluationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patientId': value['patientId'],
        'symptoms': value['symptoms'],
        'vitalSigns': CreateTriageEvaluationRequestVitalSignsToJSON(value['vitalSigns']),
    };
}

