/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface GetAuditLogs200ResponseInner
 */
export interface GetAuditLogs200ResponseInner {
    /**
     * 
     */
    evaluationId?: string;
    /**
     * 
     */
    esiCategory?: number;
    /**
     * 
     */
    justification?: string;
    /**
     * 
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the GetAuditLogs200ResponseInner interface.
 */
export function instanceOfGetAuditLogs200ResponseInner(value: object): value is GetAuditLogs200ResponseInner {
    return true;
}

export function GetAuditLogs200ResponseInnerFromJSON(json: any): GetAuditLogs200ResponseInner {
    return GetAuditLogs200ResponseInnerFromJSONTyped(json, false);
}

export function GetAuditLogs200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAuditLogs200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationId': json['evaluationId'] == null ? undefined : json['evaluationId'],
        'esiCategory': json['esiCategory'] == null ? undefined : json['esiCategory'],
        'justification': json['justification'] == null ? undefined : json['justification'],
        'timestamp': json['timestamp'] == null ? undefined : (parseDateTime(json['timestamp'])),
    };
}

export function GetAuditLogs200ResponseInnerToJSON(json: any): GetAuditLogs200ResponseInner {
    return GetAuditLogs200ResponseInnerToJSONTyped(json, false);
}

export function GetAuditLogs200ResponseInnerToJSONTyped(value?: GetAuditLogs200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluationId': value['evaluationId'],
        'esiCategory': value['esiCategory'],
        'justification': value['justification'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : serializeDateTime(value['timestamp']),
    };
}

