/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * Payload con los datos del paciente y el check explícito de consentimiento informado.
 * 
 * @export
 * @interface PatientRegistration
 */
export interface PatientRegistration {
    /**
     * 
     */
    readonly id?: string;
    /**
     * RUT chileno del paciente, validado.
     */
    rut: string;
    /**
     * 
     */
    fullName: string;
    /**
     * Signos vitales iniciales al momento del registro.
     */
    vitalSigns?: object;
    /**
     * Check explícito de consentimiento informado (obligatorio antes de procesar cualquier dato clínico).
     * 
     */
    consentGiven: boolean;
    /**
     * Marca de tiempo exacta de la aceptación del consentimiento.
     */
    consentTimestamp: Date;
}

/**
 * Check if a given object implements the PatientRegistration interface.
 */
export function instanceOfPatientRegistration(value: object): value is PatientRegistration {
    if (!('rut' in value) || value['rut'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('consentGiven' in value) || value['consentGiven'] === undefined) return false;
    if (!('consentTimestamp' in value) || value['consentTimestamp'] === undefined) return false;
    return true;
}

export function PatientRegistrationFromJSON(json: any): PatientRegistration {
    return PatientRegistrationFromJSONTyped(json, false);
}

export function PatientRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatientRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'rut': json['rut'],
        'fullName': json['fullName'],
        'vitalSigns': json['vitalSigns'] == null ? undefined : json['vitalSigns'],
        'consentGiven': json['consentGiven'],
        'consentTimestamp': (json['consentTimestamp'] == null ? json['consentTimestamp'] : parseDateTime(json['consentTimestamp'])),
    };
}

export function PatientRegistrationToJSON(json: any): PatientRegistration {
    return PatientRegistrationToJSONTyped(json, false);
}

export function PatientRegistrationToJSONTyped(value?: Omit<PatientRegistration, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rut': value['rut'],
        'fullName': value['fullName'],
        'vitalSigns': value['vitalSigns'],
        'consentGiven': value['consentGiven'],
        'consentTimestamp': value['consentTimestamp'] == null ? value['consentTimestamp'] : serializeDateTime(value['consentTimestamp']),
    };
}

