/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema de manejo de errores estructurado según RFC 7807 (Problem Details for HTTP APIs), extendido con trace_id para observabilidad según la Política de Versionado del equipo.
 * 
 * @export
 * @interface RFC7807Error
 */
export interface RFC7807Error {
    /**
     * URI que identifica el tipo de error.
     */
    type?: string;
    /**
     * 
     */
    title?: string;
    /**
     * 
     */
    status?: number;
    /**
     * 
     */
    detail?: string;
    /**
     * 
     */
    instance?: string;
    /**
     * Identificador único de la traza de la solicitud, para correlacionar logs y facilitar la observabilidad.
     * 
     */
    traceId?: string;
}

/**
 * Check if a given object implements the RFC7807Error interface.
 */
export function instanceOfRFC7807Error(value: object): value is RFC7807Error {
    return true;
}

export function RFC7807ErrorFromJSON(json: any): RFC7807Error {
    return RFC7807ErrorFromJSONTyped(json, false);
}

export function RFC7807ErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RFC7807Error {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
    };
}

export function RFC7807ErrorToJSON(json: any): RFC7807Error {
    return RFC7807ErrorToJSONTyped(json, false);
}

export function RFC7807ErrorToJSONTyped(value?: RFC7807Error | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'instance': value['instance'],
        'trace_id': value['traceId'],
    };
}

