/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Objeto que contiene la categoría ESI calculada por la IA y su justificación clínica explicable.
 * 
 * @export
 * @interface TriageResult
 */
export interface TriageResult {
    /**
     * 
     */
    readonly id?: string;
    /**
     * 
     */
    patientId?: string;
    /**
     * Categoría ESI sugerida (1 = más crítico, 5 = menos urgente).
     */
    esiCategory?: number;
    /**
     * Explicación clínica legible de por qué se sugirió esa categoría.
     */
    justification?: string;
    /**
     * 
     */
    confirmedByNurse?: boolean;
    /**
     * 
     */
    status?: TriageResultStatusEnum;
}


/**
 * @export
 */
export const TriageResultStatusEnum = {
    Pending: 'pending',
    AiSuggested: 'ai_suggested',
    Confirmed: 'confirmed',
    ManualFallback: 'manual_fallback',
} as const;
export type TriageResultStatusEnum = typeof TriageResultStatusEnum[keyof typeof TriageResultStatusEnum];


/**
 * Check if a given object implements the TriageResult interface.
 */
export function instanceOfTriageResult(value: object): value is TriageResult {
    return true;
}

export function TriageResultFromJSON(json: any): TriageResult {
    return TriageResultFromJSONTyped(json, false);
}

export function TriageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'patientId': json['patientId'] == null ? undefined : json['patientId'],
        'esiCategory': json['esiCategory'] == null ? undefined : json['esiCategory'],
        'justification': json['justification'] == null ? undefined : json['justification'],
        'confirmedByNurse': json['confirmedByNurse'] == null ? undefined : json['confirmedByNurse'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TriageResultToJSON(json: any): TriageResult {
    return TriageResultToJSONTyped(json, false);
}

export function TriageResultToJSONTyped(value?: Omit<TriageResult, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patientId': value['patientId'],
        'esiCategory': value['esiCategory'],
        'justification': value['justification'],
        'confirmedByNurse': value['confirmedByNurse'],
        'status': value['status'],
    };
}

