/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTriageEvaluationRequest
 */
export interface UpdateTriageEvaluationRequest {
    /**
     * 
     */
    confirmedByNurse?: boolean;
    /**
     * Categoría ESI asignada manualmente si aplica fallback.
     */
    manualEsiCategory?: number;
}

/**
 * Check if a given object implements the UpdateTriageEvaluationRequest interface.
 */
export function instanceOfUpdateTriageEvaluationRequest(value: object): value is UpdateTriageEvaluationRequest {
    return true;
}

export function UpdateTriageEvaluationRequestFromJSON(json: any): UpdateTriageEvaluationRequest {
    return UpdateTriageEvaluationRequestFromJSONTyped(json, false);
}

export function UpdateTriageEvaluationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTriageEvaluationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'confirmedByNurse': json['confirmedByNurse'] == null ? undefined : json['confirmedByNurse'],
        'manualEsiCategory': json['manualEsiCategory'] == null ? undefined : json['manualEsiCategory'],
    };
}

export function UpdateTriageEvaluationRequestToJSON(json: any): UpdateTriageEvaluationRequest {
    return UpdateTriageEvaluationRequestToJSONTyped(json, false);
}

export function UpdateTriageEvaluationRequestToJSONTyped(value?: UpdateTriageEvaluationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confirmedByNurse': value['confirmedByNurse'],
        'manualEsiCategory': value['manualEsiCategory'],
    };
}

