/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API para el sistema de apoyo a la priorización clínica MediTriage. Permite el registro de pacientes, la solicitud de evaluaciones de triage asistidas por IA, la consulta del tablero priorizado en tiempo real, y la auditoría de decisiones automatizadas. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateTriageEvaluationRequest,
    CreateTriageEvaluationRequestFromJSON,
    CreateTriageEvaluationRequestToJSON,
} from '../models/CreateTriageEvaluationRequest';
import {
    type GetAuditLogs200ResponseInner,
    GetAuditLogs200ResponseInnerFromJSON,
    GetAuditLogs200ResponseInnerToJSON,
} from '../models/GetAuditLogs200ResponseInner';
import {
    type PatientRegistration,
    PatientRegistrationFromJSON,
    PatientRegistrationToJSON,
} from '../models/PatientRegistration';
import {
    type RFC7807Error,
    RFC7807ErrorFromJSON,
    RFC7807ErrorToJSON,
} from '../models/RFC7807Error';
import {
    type TriageResult,
    TriageResultFromJSON,
    TriageResultToJSON,
} from '../models/TriageResult';
import {
    type UpdateTriageEvaluationRequest,
    UpdateTriageEvaluationRequestFromJSON,
    UpdateTriageEvaluationRequestToJSON,
} from '../models/UpdateTriageEvaluationRequest';

export interface CreateTriageEvaluationOperationRequest {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    createTriageEvaluationRequest: CreateTriageEvaluationRequest;
}

export interface GetAuditLogsRequest {
    /**
     * 
     */
    from?: Date;
    /**
     * 
     */
    to?: Date;
}

export interface RegisterPatientRequest {
    /**
     * Clave única generada por el cliente para evitar registros duplicados si la solicitud se reenvía (ej. por mala conexión).
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    patientRegistration: Omit<PatientRegistration, 'id'>;
}

export interface UpdateTriageEvaluationOperationRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    updateTriageEvaluationRequest: UpdateTriageEvaluationRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTriageEvaluation without sending the request
     */
    async createTriageEvaluationRequestOpts(requestParameters: CreateTriageEvaluationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createTriageEvaluation().'
            );
        }

        if (requestParameters['createTriageEvaluationRequest'] == null) {
            throw new runtime.RequiredError(
                'createTriageEvaluationRequest',
                'Required parameter "createTriageEvaluationRequest" was null or undefined when calling createTriageEvaluation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/triage-evaluations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTriageEvaluationRequestToJSON(requestParameters['createTriageEvaluationRequest']),
        };
    }

    /**
     * Envía los síntomas y signos vitales del paciente para que el motor de IA sugiera la categoría ESI y su justificación clínica (mapea Historias 1 y 2: Sugerencia ESI automatizada y Justificación clínica explicable). 
     * Solicitar una evaluación de triage asistida por IA
     */
    async createTriageEvaluationRaw(requestParameters: CreateTriageEvaluationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriageResult>> {
        const requestOptions = await this.createTriageEvaluationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriageResultFromJSON(jsonValue));
    }

    /**
     * Envía los síntomas y signos vitales del paciente para que el motor de IA sugiera la categoría ESI y su justificación clínica (mapea Historias 1 y 2: Sugerencia ESI automatizada y Justificación clínica explicable). 
     * Solicitar una evaluación de triage asistida por IA
     */
    async createTriageEvaluation(requestParameters: CreateTriageEvaluationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriageResult> {
        const response = await this.createTriageEvaluationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAuditLogs without sending the request
     */
    async getAuditLogsRequestOpts(requestParameters: GetAuditLogsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = runtime.serializeDate(requestParameters['from'] as any);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = runtime.serializeDate(requestParameters['to'] as any);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/audit-logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Devuelve el registro inmutable de recomendaciones de la IA para fines de trazabilidad (mapea Historia 5, retención de 5 años). Historia Must Have — crítica para cumplir la Ley 21.719. 
     * Consultar el registro de auditoría de decisiones IA
     */
    async getAuditLogsRaw(requestParameters: GetAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAuditLogs200ResponseInner>>> {
        const requestOptions = await this.getAuditLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAuditLogs200ResponseInnerFromJSON));
    }

    /**
     * Devuelve el registro inmutable de recomendaciones de la IA para fines de trazabilidad (mapea Historia 5, retención de 5 años). Historia Must Have — crítica para cumplir la Ley 21.719. 
     * Consultar el registro de auditoría de decisiones IA
     */
    async getAuditLogs(requestParameters: GetAuditLogsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAuditLogs200ResponseInner>> {
        const response = await this.getAuditLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTriageBoard without sending the request
     */
    async getTriageBoardRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/triage-board`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Devuelve el listado de pacientes priorizados en tiempo real (mapea Historia 4, tablero dinámico del médico jefe). Historia Must Have según priorización MoSCoW. 
     * Consultar el tablero de pacientes priorizados
     */
    async getTriageBoardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TriageResult>>> {
        const requestOptions = await this.getTriageBoardRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TriageResultFromJSON));
    }

    /**
     * Devuelve el listado de pacientes priorizados en tiempo real (mapea Historia 4, tablero dinámico del médico jefe). Historia Must Have según priorización MoSCoW. 
     * Consultar el tablero de pacientes priorizados
     */
    async getTriageBoard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TriageResult>> {
        const response = await this.getTriageBoardRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerPatient without sending the request
     */
    async registerPatientRequestOpts(requestParameters: RegisterPatientRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling registerPatient().'
            );
        }

        if (requestParameters['patientRegistration'] == null) {
            throw new runtime.RequiredError(
                'patientRegistration',
                'Required parameter "patientRegistration" was null or undefined when calling registerPatient().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/patients`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PatientRegistrationToJSON(requestParameters['patientRegistration']),
        };
    }

    /**
     * Registra un paciente (mapea Historia 3: registro y validación de RUT) junto con el check explícito de consentimiento informado. Historia Must Have según priorización MoSCoW — obligatoria por la Ley 19.628 para procesar datos sensibles de salud. 
     * Registrar un nuevo paciente
     */
    async registerPatientRaw(requestParameters: RegisterPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PatientRegistration>> {
        const requestOptions = await this.registerPatientRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PatientRegistrationFromJSON(jsonValue));
    }

    /**
     * Registra un paciente (mapea Historia 3: registro y validación de RUT) junto con el check explícito de consentimiento informado. Historia Must Have según priorización MoSCoW — obligatoria por la Ley 19.628 para procesar datos sensibles de salud. 
     * Registrar un nuevo paciente
     */
    async registerPatient(requestParameters: RegisterPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PatientRegistration> {
        const response = await this.registerPatientRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTriageEvaluation without sending the request
     */
    async updateTriageEvaluationRequestOpts(requestParameters: UpdateTriageEvaluationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTriageEvaluation().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateTriageEvaluation().'
            );
        }

        if (requestParameters['updateTriageEvaluationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTriageEvaluationRequest',
                'Required parameter "updateTriageEvaluationRequest" was null or undefined when calling updateTriageEvaluation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/triage-evaluations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTriageEvaluationRequestToJSON(requestParameters['updateTriageEvaluationRequest']),
        };
    }

    /**
     * Permite a la enfermera de triage confirmar la sugerencia ESI generada por la IA, o aplicar el fallback manual si el motor de IA no respondió. Este endpoint no corresponde a una historia explícita del backlog de la S02, sino que implementa el requisito de disponibilidad con fallback manual definido en el ADR 0002 (NFR de Martín G.: SLA 99.5% + fallback si el motor de IA falla). 
     * Confirmar o aplicar fallback manual sobre una evaluación
     */
    async updateTriageEvaluationRaw(requestParameters: UpdateTriageEvaluationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriageResult>> {
        const requestOptions = await this.updateTriageEvaluationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriageResultFromJSON(jsonValue));
    }

    /**
     * Permite a la enfermera de triage confirmar la sugerencia ESI generada por la IA, o aplicar el fallback manual si el motor de IA no respondió. Este endpoint no corresponde a una historia explícita del backlog de la S02, sino que implementa el requisito de disponibilidad con fallback manual definido en el ADR 0002 (NFR de Martín G.: SLA 99.5% + fallback si el motor de IA falla). 
     * Confirmar o aplicar fallback manual sobre una evaluación
     */
    async updateTriageEvaluation(requestParameters: UpdateTriageEvaluationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriageResult> {
        const response = await this.updateTriageEvaluationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
